"""GitHub Webhook endpoint handler."""

from __future__ import annotations

import asyncio
import logging
import os
import uuid
from typing import Any
from fastapi import APIRouter, Depends, Header, HTTPException, Request, Response, status
from sqlalchemy.orm import Session

from mathlore_forge.config import ensure_env_loaded
from mathlore_forge.storage.db import AgentRunRecord, IssueRecord, RunStatus, RunType, get_db, init_db
from mathlore_forge.storage.gcs_sync import sync_db_to_gcs_now
from mathlore_forge.workflows.authoring_flow import AuthoringFlow
from mathlore_forge.workflows.curation_flow import CurationFlow
from mathlore_forge.workflows.flywheel_flow import FlywheelFlow
from mathlore_forge.workflows.github_client import FORGE_BOT_MARKER, GitHubClient, GitHubIssue
from mathlore_forge.workflows.intent import IssueIntent, classify_issue_intent
from mathlore_forge.workflows.review_flow import ReviewFlow

ensure_env_loaded()
logger = logging.getLogger(__name__)

router = APIRouter(prefix="/webhooks", tags=["Webhooks"])

ALLOWED_AUTHOR = os.getenv("ALLOWED_GITHUB_AUTHOR", "DominicKramer").strip().lower()
WEBHOOK_SECRET = os.getenv("GITHUB_WEBHOOK_SECRET", "")
FORGE_LABEL = os.getenv("FORGE_ISSUE_LABEL", "forge").strip().lower()


def is_bot_comment(body: str) -> bool:
    """Checks whether the comment was generated by the Forge bot itself to prevent self-trigger loops."""
    if not body:
        return False
    trimmed = body.strip()
    if trimmed.startswith(FORGE_BOT_MARKER) or FORGE_BOT_MARKER in trimmed or "<!-- forge-bot -->" in trimmed:
        return True
    lower = trimmed.lower()
    if (
        lower.startswith("### 🤖 mathlore forge")
        or lower.startswith("### 🔄 incorporating feedback")
        or lower.startswith("### 🚀 plan approved")
        or lower.startswith("### ⚠️ mathlore forge")
        or lower.startswith("### ⚠️ refinement error")
        or lower.startswith("### ⚠️ plan execution error")
        or "view run on mathlore forge dashboard" in lower
        or "*authored by mathlore forge" in lower
    ):
        return True
    return False


def get_dashboard_base_url(request: Request | None = None) -> str:
    """Computes the dashboard base URL for notifications and links."""
    env_url = os.getenv("DASHBOARD_URL", "").strip().rstrip("/")
    if env_url:
        return env_url
    if request:
        proto = request.headers.get("x-forwarded-proto", "https")
        host = request.headers.get("x-forwarded-host") or request.headers.get("host") or request.url.netloc
        if host:
            return f"{proto}://{host}".rstrip("/")
    return "https://mathlore-forge-web-bx7vyixa6a-uc.a.run.app"


def is_authorized_user(username: str | None) -> bool:
    """Verifies that the GitHub username matches Dominic Kramer."""
    if not username:
        return False
    return username.lower() == ALLOWED_AUTHOR or username.lower() == "dominickramer"


def has_forge_marker(issue_data: dict[str, Any]) -> bool:
    """Checks whether the issue has the forge label or title marker."""
    title = issue_data.get("title", "").lower()
    if "[forge]" in title:
        return True

    labels = issue_data.get("labels", [])
    for label in labels:
        name = label.get("name", "").lower() if isinstance(label, dict) else str(label).lower()
        if name in (FORGE_LABEL, "forge-task", "mathlore-forge"):
            return True

    return False


_issues_lock = asyncio.Lock()
_active_issue_initializations: set[str] = set()
_processed_comment_ids: set[int] = set()


@router.post("/github")
async def github_webhook(
    request: Request,
    x_github_event: str | None = Header(None, alias="X-GitHub-Event"),
    x_hub_signature_256: str | None = Header(None, alias="X-Hub-Signature-256"),
    db: Session = Depends(get_db),
) -> dict[str, Any]:
    """Receives and processes GitHub Webhook events."""
    body_bytes = await request.body()

    # 1. Verify HMAC signature if secret configured
    if WEBHOOK_SECRET:
        valid = GitHubClient.verify_webhook_signature(body_bytes, x_hub_signature_256, WEBHOOK_SECRET)
        if not valid:
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid webhook signature")

    payload = await request.json()
    event_type = x_github_event or request.headers.get("x-github-event")
    base_url = get_dashboard_base_url(request)

    sender = payload.get("sender", {}).get("login", "")
    repo_full_name = payload.get("repository", {}).get("full_name", "mathlingua/mathlore")

    # 2. Handle Issues Event (Initial Trigger: Planning vs Direct Authoring)
    if event_type == "issues":
        action = payload.get("action")
        issue = payload.get("issue", {})
        issue_number = issue.get("number")
        author = issue.get("user", {}).get("login", "")

        # Only process if action is opened or labeled, and author/sender is authorized
        if action in ("opened", "labeled"):
            if is_authorized_user(author) or is_authorized_user(sender):
                # If event is 'labeled', verify that the added label is a Forge trigger
                if action == "labeled":
                    added_label = payload.get("label", {}).get("name", "").lower()
                    if added_label not in (FORGE_LABEL, "forge-task", "mathlore-forge"):
                        return {"status": "ignored", "reason": "non_forge_label"}

                if has_forge_marker(issue):
                    issue_key = f"{repo_full_name}#{issue_number}"
                    async with _issues_lock:
                        # 1. In-memory deduplication (catches race conditions between opened + labeled events)
                        if issue_key in _active_issue_initializations:
                            logger.info("Ignoring duplicate issues webhook for %s (already initializing)", issue_key)
                            return {"status": "ignored", "reason": "already_initializing"}

                        # 2. Database check: don't restart if already tracked
                        db_mgr = init_db()
                        with db_mgr.get_session() as session:
                            rec = (
                                session.query(IssueRecord)
                                .filter_by(repo=repo_full_name, issue_number=issue_number)
                                .first()
                            )
                            if rec:
                                logger.info(
                                    "Ignoring issues webhook for %s (already tracked with status=%s, plan_status=%s)",
                                    issue_key,
                                    rec.status,
                                    rec.plan_status,
                                )
                                return {"status": "ignored", "reason": "already_tracked"}

                            title = issue.get("title", "")
                            body = issue.get("body", "") or ""
                            author_login = issue.get("user", {}).get("login", "") or sender or "DominicKramer"
                            labels = [
                                lbl.get("name", "") if isinstance(lbl, dict) else str(lbl)
                                for lbl in issue.get("labels", [])
                            ]
                            intent = classify_issue_intent(title=title, body=body, labels=labels)
                            initial_status = "PLANNING" if intent == IssueIntent.HIGHER_ORDER_PLANNING else "IN_PROGRESS"
                            new_issue_record = IssueRecord(
                                repo=repo_full_name,
                                issue_number=issue_number,
                                title=title,
                                body=body,
                                author=author_login,
                                status=initial_status,
                                plan_status="PLANNING" if intent == IssueIntent.HIGHER_ORDER_PLANNING else None,
                            )
                            session.add(new_issue_record)
                            session.commit()

                        _active_issue_initializations.add(issue_key)

                    if intent == IssueIntent.HIGHER_ORDER_PLANNING:
                        asyncio.create_task(
                            _run_curation_planning_task(repo_full_name, issue_number, issue_data=issue, base_url=base_url)
                        )
                        return {
                            "status": "accepted",
                            "workflow": "curation_planning",
                            "repo": repo_full_name,
                            "issue": issue_number,
                        }
                    else:
                        asyncio.create_task(
                            _run_authoring_task(repo_full_name, issue_number, issue_data=issue, base_url=base_url)
                        )
                        return {
                            "status": "accepted",
                            "workflow": "authoring",
                            "repo": repo_full_name,
                            "issue": issue_number,
                        }

    # 3. Handle Pull Request Review Event (Approval / Changes Requested)
    elif event_type == "pull_request_review":
        action = payload.get("action")
        pr = payload.get("pull_request", {})
        review = payload.get("review", {})
        review_state = review.get("state", "").lower()  # approved, changes_requested, commented
        pr_number = pr.get("number")
        review_author = review.get("user", {}).get("login", "")

        if action == "submitted" and is_authorized_user(review_author):
            if review_state == "approved":
                # Step 8 & 9: Trigger Flywheel and Merge
                asyncio.create_task(
                    _run_flywheel_task(repo_full_name, pr_number, base_url=base_url)
                )
                return {
                    "status": "accepted",
                    "workflow": "flywheel_and_merge",
                    "repo": repo_full_name,
                    "pr": pr_number,
                }
            elif review_state in ("changes_requested", "commented"):
                # Step 5: Address Comments
                asyncio.create_task(
                    _run_review_task(repo_full_name, pr_number)
                )
                return {
                    "status": "accepted",
                    "workflow": "address_review_comments",
                    "repo": repo_full_name,
                    "pr": pr_number,
                }

    # 4. Handle Issue/PR Comments (Slash Commands & Interactive Proposal Refinement)
    elif event_type == "issue_comment":
        action = payload.get("action")
        comment = payload.get("comment", {})
        raw_comment_body = comment.get("body", "")
        comment_body = raw_comment_body.lower().strip()
        comment_author = comment.get("user", {}).get("login", "")
        issue = payload.get("issue", {})
        issue_or_pr_number = issue.get("number")
        is_pr = "pull_request" in issue

        # Ignore any comments posted by Mathlore Forge itself to prevent recursive self-trigger loops!
        if is_bot_comment(raw_comment_body):
            logger.info("Ignoring issue_comment created by Forge bot on %s#%s", repo_full_name, issue_or_pr_number)
            return {"status": "ignored", "reason": "bot_comment"}

        if action == "created" and is_authorized_user(comment_author):
            if is_pr:
                if "/forge address" in comment_body or "@mathlore-forge address" in comment_body:
                    asyncio.create_task(
                        _run_review_task(repo_full_name, issue_or_pr_number)
                    )
                    return {
                        "status": "accepted",
                        "workflow": "address_review_comments",
                        "pr": issue_or_pr_number,
                    }
                elif any(cmd in comment_body for cmd in ("/forge accept", "/forge approve", "/forge merge", "@mathlore-forge accept", "@mathlore-forge approve")):
                    asyncio.create_task(
                        _run_flywheel_task(repo_full_name, issue_or_pr_number, base_url=base_url)
                    )
                    return {
                        "status": "accepted",
                        "workflow": "flywheel_and_merge",
                        "pr": issue_or_pr_number,
                    }
            else:
                # Dominic interacting with an Issue (Planning, Refinement, Execution)
                if any(cmd in comment_body for cmd in ("/forge execute", "/forge approve-plan", "/forge approve", "/forge accept", "@mathlore-forge execute", "@mathlore-forge approve", "@mathlore-forge accept")):
                    asyncio.create_task(
                        _run_curation_execution_task(repo_full_name, issue_or_pr_number, base_url=base_url)
                    )
                    return {
                        "status": "accepted",
                        "workflow": "curation_plan_execution",
                        "repo": repo_full_name,
                        "issue": issue_or_pr_number,
                    }
                elif "/forge plan" in comment_body or "@mathlore-forge plan" in comment_body:
                    asyncio.create_task(
                        _run_curation_planning_task(repo_full_name, issue_or_pr_number, issue_data=issue, base_url=base_url)
                    )
                    return {
                        "status": "accepted",
                        "workflow": "curation_planning",
                        "repo": repo_full_name,
                        "issue": issue_or_pr_number,
                    }
                else:
                    # Check if this issue is tracked and awaiting review on an existing plan
                    db_mgr = init_db()
                    has_active_plan = False
                    with db_mgr.get_session() as session:
                        rec = (
                            session.query(IssueRecord)
                            .filter_by(repo=repo_full_name, issue_number=issue_or_pr_number)
                            .first()
                        )
                        # Only refine if the initial plan is already formulated and awaiting approval
                        if rec and rec.plan_status in ("AWAITING_APPROVAL", "REFINING") and rec.plan_markdown:
                            has_active_plan = True

                    if has_active_plan:
                        raw_feedback = comment.get("body", "")
                        asyncio.create_task(
                            _run_curation_refinement_task(
                                repo_full_name, issue_or_pr_number, feedback=raw_feedback, base_url=base_url
                            )
                        )
                        return {
                            "status": "accepted",
                            "workflow": "curation_plan_refinement",
                            "repo": repo_full_name,
                            "issue": issue_or_pr_number,
                        }

    return {"status": "ignored", "event": event_type}


async def _run_authoring_task(
    repo: str,
    issue_number: int,
    issue_data: dict[str, Any] | None = None,
    base_url: str = "https://mathlore-forge-web-bx7vyixa6a-uc.a.run.app",
) -> None:
    """Background execution runner for authoring flow."""
    db_mgr = init_db()
    with db_mgr.get_session() as session:
        flow = AuthoringFlow()
        initial_issue = None
        if issue_data and issue_data.get("title"):
            labels = []
            for item in issue_data.get("labels", []):
                if isinstance(item, dict):
                    labels.append(item.get("name", ""))
                elif isinstance(item, str):
                    labels.append(item)
            initial_issue = GitHubIssue(
                number=issue_number,
                title=issue_data.get("title", ""),
                body=issue_data.get("body", "") or "",
                author=issue_data.get("user", {}).get("login", "") or issue_data.get("author", ""),
                labels=labels,
                state=issue_data.get("state", "open"),
                html_url=issue_data.get("html_url", ""),
            )

        run_id = f"run_auth_{uuid.uuid4().hex[:12]}"
        run_url = f"{base_url}/runs/{run_id}"

        # 1. Post immediate acknowledgment on GitHub issue
        try:
            ack_msg = (
                f"### 🤖 Mathlore Forge Agent Initialized\n\n"
                f"I've picked up this issue and am authoring the requested Mathlingua content.\n\n"
                f"- **Run ID**: `{run_id}`\n"
                f"- **Workflow**: `Direct Authoring`\n"
                f"- **Live Dashboard & Telemetry**: [View Run on Mathlore Forge Dashboard]({run_url})\n\n"
                f"*I will run `mlg check`, validate the mathematical formulations, and open a Pull Request when complete.*"
            )
            await flow.github_client.create_issue_comment(repo=repo, issue_or_pr_number=issue_number, body=ack_msg)
        except Exception as ack_err:
            logger.warning("Failed to post initial acknowledgment comment for %s#%s: %s", repo, issue_number, ack_err)

        try:
            await flow.execute(
                repo=repo,
                issue_number=issue_number,
                db_session=session,
                run_id=run_id,
                initial_issue=initial_issue,
                dashboard_url=run_url,
            )
        except Exception as e:
            logger.error("Authoring flow failed for %s#%s: %s", repo, issue_number, e, exc_info=True)
            try:
                rec = session.query(AgentRunRecord).filter_by(id=run_id).first()
                if not rec:
                    rec = AgentRunRecord(
                        id=run_id,
                        run_type=RunType.AUTHORING,
                        status=RunStatus.FAILED,
                        repo=repo,
                        issue_number=issue_number,
                        prompt=f"Direct authoring for #{issue_number}",
                        error_message=str(e),
                    )
                    session.add(rec)
                else:
                    rec.status = RunStatus.FAILED
                    rec.error_message = str(e)
                session.commit()
                sync_db_to_gcs_now()
            except Exception as dberr:
                logger.warning("Could not persist failed run record %s: %s", run_id, dberr)

            try:
                err_msg = (
                    f"### ⚠️ Mathlore Forge Agent Encountered an Error\n\n"
                    f"An error occurred during authoring:\n"
                    f"> {e}\n\n"
                    f"- **Run ID**: `{run_id}`\n"
                    f"- **Telemetry & Logs**: [Inspect Error on Dashboard]({run_url})\n"
                )
                await flow.github_client.create_issue_comment(repo=repo, issue_or_pr_number=issue_number, body=err_msg)
            except Exception:
                pass


async def _run_curation_planning_task(
    repo: str,
    issue_number: int,
    issue_data: dict[str, Any] | None = None,
    base_url: str = "https://mathlore-forge-web-bx7vyixa6a-uc.a.run.app",
) -> None:
    """Background execution runner for curation and architectural planning flow."""
    db_mgr = init_db()
    with db_mgr.get_session() as session:
        flow = CurationFlow()
        title = ""
        body = ""
        author = "DominicKramer"
        if issue_data and issue_data.get("title"):
            title = issue_data.get("title", "")
            body = issue_data.get("body", "") or ""
            author = issue_data.get("user", {}).get("login", "") or issue_data.get("author", "DominicKramer")
        else:
            try:
                issue = await flow.github_client.get_issue(repo, issue_number)
                title = issue.title
                body = issue.body
                author = issue.author
            except Exception as e:
                logger.warning("Could not fetch issue %s#%s from GitHub: %s", repo, issue_number, e)

        run_id = f"run_plan_{uuid.uuid4().hex[:12]}"
        run_url = f"{base_url}/runs/{run_id}"

        # 1. Post immediate acknowledgment on GitHub issue
        try:
            ack_msg = (
                f"### 🤖 Mathlore Forge Agent Initialized\n\n"
                f"I've picked up this issue and am analyzing the repository architecture to formulate a curation plan.\n\n"
                f"- **Run ID**: `{run_id}`\n"
                f"- **Workflow**: `Curation & Architectural Planning`\n"
                f"- **Live Dashboard & Telemetry**: [View Run on Mathlore Forge Dashboard]({run_url})\n\n"
                f"*I will post the proposed mathematical structure and plan here once ready for your review.*"
            )
            await flow.github_client.create_issue_comment(repo=repo, issue_or_pr_number=issue_number, body=ack_msg)
        except Exception as ack_err:
            logger.warning("Failed to post initial acknowledgment comment for %s#%s: %s", repo, issue_number, ack_err)

        try:
            await flow.handle_initial_proposal(
                repo=repo,
                issue_number=issue_number,
                issue_title=title,
                issue_body=body,
                author=author,
                db_session=session,
                run_id=run_id,
                dashboard_url=run_url,
            )
        except Exception as e:
            logger.error("Curation planning failed for %s#%s: %s", repo, issue_number, e, exc_info=True)
            try:
                rec = session.query(AgentRunRecord).filter_by(id=run_id).first()
                if not rec:
                    rec = AgentRunRecord(
                        id=run_id,
                        run_type=RunType.PLANNING,
                        status=RunStatus.FAILED,
                        repo=repo,
                        issue_number=issue_number,
                        prompt=f"Curation planning for #{issue_number}",
                        error_message=str(e),
                    )
                    session.add(rec)
                else:
                    rec.status = RunStatus.FAILED
                    rec.error_message = str(e)
                session.commit()
                sync_db_to_gcs_now()
            except Exception as dberr:
                logger.warning("Could not persist failed run record %s: %s", run_id, dberr)

            try:
                err_msg = (
                    f"### ⚠️ Mathlore Forge Agent Encountered an Error\n\n"
                    f"An error occurred while drafting the curation plan:\n"
                    f"> {e}\n\n"
                    f"- **Run ID**: `{run_id}`\n"
                    f"- **Telemetry & Logs**: [Inspect Error on Dashboard]({run_url})\n"
                )
                await flow.github_client.create_issue_comment(repo=repo, issue_or_pr_number=issue_number, body=err_msg)
            except Exception:
                pass


async def _run_curation_refinement_task(
    repo: str,
    issue_number: int,
    feedback: str,
    base_url: str = "https://mathlore-forge-web-bx7vyixa6a-uc.a.run.app",
) -> None:
    """Background execution runner for proposal refinement based on Dominic Kramer's feedback."""
    db_mgr = init_db()
    with db_mgr.get_session() as session:
        flow = CurationFlow()
        run_id = f"run_refine_{uuid.uuid4().hex[:12]}"
        run_url = f"{base_url}/runs/{run_id}"

        # 1. Immediate acknowledgment
        try:
            ack_msg = (
                f"### 🔄 Incorporating Feedback\n\n"
                f"I've received your feedback and am updating the curation proposal.\n\n"
                f"- **Run ID**: `{run_id}`\n"
                f"- **Live Dashboard & Telemetry**: [View Run on Mathlore Forge Dashboard]({run_url})"
            )
            await flow.github_client.create_issue_comment(repo=repo, issue_or_pr_number=issue_number, body=ack_msg)
        except Exception as ack_err:
            logger.warning("Failed to post refinement acknowledgment for %s#%s: %s", repo, issue_number, ack_err)

        try:
            await flow.handle_proposal_refinement(
                repo=repo,
                issue_number=issue_number,
                user_feedback=feedback,
                db_session=session,
                run_id=run_id,
                dashboard_url=run_url,
            )
        except Exception as e:
            logger.error("Curation refinement failed for %s#%s: %s", repo, issue_number, e, exc_info=True)
            try:
                rec = session.query(AgentRunRecord).filter_by(id=run_id).first()
                if not rec:
                    rec = AgentRunRecord(
                        id=run_id,
                        run_type=RunType.REFINEMENT,
                        status=RunStatus.FAILED,
                        repo=repo,
                        issue_number=issue_number,
                        prompt=f"Proposal refinement for #{issue_number}",
                        error_message=str(e),
                    )
                    session.add(rec)
                else:
                    rec.status = RunStatus.FAILED
                    rec.error_message = str(e)
                session.commit()
                sync_db_to_gcs_now()
            except Exception as dberr:
                logger.warning("Could not persist failed run record %s: %s", run_id, dberr)

            try:
                err_msg = (
                    f"### ⚠️ Refinement Error\n\n"
                    f"An error occurred while refining the plan:\n"
                    f"> {e}\n\n"
                    f"- **Run ID**: `{run_id}`\n"
                    f"- **Telemetry & Logs**: [Inspect Error on Dashboard]({run_url})\n"
                )
                await flow.github_client.create_issue_comment(repo=repo, issue_or_pr_number=issue_number, body=err_msg)
            except Exception:
                pass


async def _run_curation_execution_task(
    repo: str,
    issue_number: int,
    base_url: str = "https://mathlore-forge-web-bx7vyixa6a-uc.a.run.app",
) -> None:
    """Background execution runner for executing an approved plan."""
    db_mgr = init_db()
    with db_mgr.get_session() as session:
        flow = CurationFlow()
        run_id = f"run_exec_{uuid.uuid4().hex[:12]}"
        run_url = f"{base_url}/runs/{run_id}"

        try:
            await flow.handle_plan_execution(
                repo=repo,
                issue_number=issue_number,
                db_session=session,
                run_id=run_id,
                dashboard_url=run_url,
            )
        except Exception as e:
            logger.error("Plan execution failed for %s#%s: %s", repo, issue_number, e, exc_info=True)
            try:
                rec = session.query(AgentRunRecord).filter_by(id=run_id).first()
                if not rec:
                    rec = AgentRunRecord(
                        id=run_id,
                        run_type=RunType.PLAN_EXECUTION,
                        status=RunStatus.FAILED,
                        repo=repo,
                        issue_number=issue_number,
                        prompt=f"Execute approved plan for #{issue_number}",
                        error_message=str(e),
                    )
                    session.add(rec)
                else:
                    rec.status = RunStatus.FAILED
                    rec.error_message = str(e)
                session.commit()
                sync_db_to_gcs_now()
            except Exception as dberr:
                logger.warning("Could not persist failed run record %s: %s", run_id, dberr)

            try:
                err_msg = (
                    f"### ⚠️ Plan Execution Error\n\n"
                    f"An error occurred while executing the approved plan:\n"
                    f"> {e}\n\n"
                    f"- **Run ID**: `{run_id}`\n"
                    f"- **Telemetry & Logs**: [Inspect Error on Dashboard]({run_url})\n"
                )
                await flow.github_client.create_issue_comment(repo=repo, issue_or_pr_number=issue_number, body=err_msg)
            except Exception:
                pass


async def _run_review_task(repo: str, pr_number: int) -> None:
    """Background execution runner for review comment resolution."""
    db_mgr = init_db()
    with db_mgr.get_session() as session:
        flow = ReviewFlow()
        try:
            await flow.execute(repo=repo, pr_number=pr_number, db_session=session)
        except Exception as e:
            logger.error("Review resolution flow failed for %s#%s: %s", repo, pr_number, e, exc_info=True)


async def _run_flywheel_task(
    repo: str,
    pr_number: int,
    base_url: str = "https://mathlore-forge-web-bx7vyixa6a-uc.a.run.app",
) -> None:
    """Background execution runner for flywheel, pre-merge validation, and PR merging."""
    db_mgr = init_db()
    with db_mgr.get_session() as session:
        flow = FlywheelFlow()
        run_id = f"run_flywheel_{uuid.uuid4().hex[:12]}"
        run_url = f"{base_url}/runs/{run_id}"
        try:
            await flow.execute(
                mathlore_repo=repo,
                pr_number=pr_number,
                db_session=session,
                run_id=run_id,
                dashboard_url=run_url,
            )
        except Exception as e:
            logger.error("Flywheel flow failed for %s#%s: %s", repo, pr_number, e, exc_info=True)
            try:
                err_msg = (
                    f"### ⚠️ Mathlore Forge Acceptance / Merge Error\n\n"
                    f"An error occurred while validating or merging PR #{pr_number}:\n"
                    f"> {e}\n\n"
                    f"- **Run ID**: `{run_id}`\n"
                    f"- **Telemetry & Logs**: [Inspect Error on Dashboard]({run_url})\n"
                )
                await flow.github_client.create_issue_comment(repo=repo, issue_or_pr_number=pr_number, body=err_msg)
            except Exception:
                pass
